export const services = [
  {
    name: "Roda de Buteco",
    items: [
      "Filé de peito de frango empanado",
      "Batata frita",
      "Polenta frita",
      "Tilápia frita",
      "Linguiça churrasco",
      "Linguiça caseira",
      "Torresmo",
      "Mandioquita",
      "Costelinha de porco",
      "Banana frita",
      "Barquete",
      "Torradas com antepasto e patês variados",
      "Batata baby",
      "Mini hambúrguer",
      "Mini cachorro quente",
      "Mini churros",
      "Mini pizza",
      "Ovo de codorna",
      "Anel de cebola",
      "Salgadinhos",
      "Tábua de frios (lombo, salaminho, presunto, queijos variados, azeitona, etc.)",
    ],
  },
  {
    name: "Jantar",
    items: [
      "Arroz",
      "Feijão tropeiro",
      "Boi ao molho madeira",
      "Frango",
      "Carne de porco assada",
      "Strogonoff de frango ou boi",
      "Salada com folhas, frutas e verduras",
      "Farofas",
      "Maionese",
      "Salpicão",
      "Tilápia",
      "Batata Alemã",
      "Chucrute",
      "Vinagrete",
      "Salsichão",
      "Joelho de porco",
    ],
  },
  {
    name: "Almoço",
    items: [
      "Arroz",
      "Feijão tropeiro",
      "Boi ao molho madeira",
      "Frango",
      "Carne de porco assada",
      "Strogonoff de frango ou boi",
      "Salada com folhas, frutas e verduras",
      "Farofas",
      "Maionese",
      "Salpicão",
      "Tilápia",
      "Batata Alemã",
      "Chucrute",
      "Vinagrete",
      "Salsichão",
      "Joelho de porco",
    ],
  },
  {
    name: "Churrasco",
    items: [
      "Carne de boi (Chorizo, Contrafilé, Alcatra ou Picanha)",
      "Carne de porco",
      "Carne de frango",
      "Linguiça",
      "Pão de alho",
      "Queijo",
      "Vinagrete",
      "Feijão tropeiro",
    ],
  },
  {
    name: "Coffe Break",
    items: [
      "Cafés (c/ açúcar e sem açúcar)",
      "Leite",
      "Bolos (Laranja, cenoura, chocolate, fubá, mesclado, aipim, coco ou cuca alemão)",
      "Pães (caseiro, sal, broto de milho ou doce)",
      "Cachorro quente",
      "Mini Hambúrguer",
      "Pão de queijo",
      "Torradas",
      "Biscoitos",
      "Patês",
      "Queijos (Chimia ou minas)",
      "Presunto e queijo",
      "Salgadinhos",
      "Doces (Goiaba, mamão ou mamão com laranja",
      "Frutas (Banana, melão, melancia ou mamão)",
    ],
  },
  {
    name: "Bebidas",
    items: [
      "Suco natural 2 sabores",
      "Coca-cola",
      "Guaraná",
      "Cerveja (Brahma, Skol, Amstel)",
      "Chopp",
      "Drinks (Alcoólico ou não alcoólico)",
      "Coquetel de frutas",
    ],
  },
  {
    name: "Espaço para Evento",
    items: [
      "Espaço para até 120 pessoas. Localizado em Domingos Martins, rua Alida Lampier Schwambach nº 50 (casa de Darlene).",
    ],
  },
];
